---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
  namespace: k6-tests
spec:
  parallelism: 4
  script:
    configMap:
      name: "test"
      file: "test.js"
  arguments: --tag office=hours --out cloud
  runner:
    env:
      - name: BASE_URL
        value: https://pizza.grafana.fun
