apiVersion: v1
kind: ConfigMap
metadata:
  name: test
  namespace: default
data:
  test.js: |
    import http from 'k6/http';
    import { check } from 'k6';

    export let options = {
      vus: 1,
      duration: '50s'
    };

    export default function () {
      const result = http.get('https://quickpizza.grafana.com');
      check(result, {
        'http response status code is 200': result.status === 200,
      });
    }
