---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: k6-operator
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    tags.datadoghq.com/env: "edge"
    tags.datadoghq.com/service: "laasie-k6-operator-controller"
    tags.datadoghq.com/version: "v0.0.7-202208081725"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
        tags.datadoghq.com/env: "edge"
        tags.datadoghq.com/service: "laasie-k6-operator-controller"
        tags.datadoghq.com/version: "v0.0.7-202208081725"
    spec:
      serviceAccountName: k6-operator-controller
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: controller:latest
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
          env:
          - name: DD_ENV # Note the datadog agent only supports literal values and doesn't work when DD_* env vars are set using fieldRef, configmap, or anything else.
            value: "edge"
          - name: DD_SERVICE
            value: "laasie-k6-operator-controller"
          - name: DD_VERSION
            value: "v0.0.7-202208081725"
      terminationGracePeriodSeconds: 10
