apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-manager-rolebinding
  labels:
    {{- include "operator.labels" . }}
  annotations:
    {{- include "operator.annotations" . | default "" | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.manager.serviceAccount }}
    namespace: {{- include "operator.namespace" . -}}
{{- if .Values.authProxy.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-proxy-rolebinding
  labels:
    {{- include "operator.labels" . }}
  annotations:
    {{- include "operator.annotations" . | default "" | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.manager.serviceAccount }}
    namespace: {{- include "operator.namespace" . -}}
{{- end }}
