apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-leader-election-rolebinding
  namespace: {{- include "operator.namespace" . }}
  labels:
    {{- include "operator.labels" . }}
  annotations:
    {{- include "operator.annotations" . | default "" | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.manager.serviceAccount }}
  namespace: {{- include "operator.namespace" . }}
