apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccount }}
  namespace: {{- include "operator.namespace" . }}
  labels:
    {{- include "operator.labels" . }}
  annotations:
    {{- include "operator.annotations" . | default "" | nindent 4 }}
