---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 1
  arguments: this argument-is-invalid
  script:
    configMap:
      name: "test"
      file: "test.js"
