---
# permissions for end users to view privateloadzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privateloadzone-viewer-role
rules:
- apiGroups:
  - k6.io
  resources:
  - privateloadzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k6.io
  resources:
  - privateloadzones/status
  verbs:
  - get
