# permissions for end users to edit testruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testrun-editor-role
rules:
- apiGroups:
  - k6.io
  resources:
  - testruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - testruns/status
  verbs:
  - get
