blank_issues_enabled: true
contact_links:
  - name: Grafana Community Forum - k6-operator
    url: https://community.grafana.com/c/grafana-k6/k6-operator/73
    about: Please ask and answer questions here.
