apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k6-operator.fullname" . }}-manager-role
  labels:
    app.kubernetes.io/component: controller
    {{- include "k6-operator.labels" . | nindent 4 }}
    {{- include "k6-operator.customLabels" . | default "" | nindent 4 }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - k6s/finalizers
  - k6s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k6.io
  resources:
  - privateloadzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - privateloadzones/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k6.io
  resources:
  - privateloadzones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k6.io
  resources:
  - testruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - testruns/finalizers
  - testruns/status
  verbs:
  - get
  - patch
  - update
{{- if .Values.authProxy.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k6-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "k6-operator.labels" . | nindent 4 }}
    {{- include "k6-operator.customLabels" . | default "" | nindent 4 }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k6-operator.fullname" . }}-proxy-role
  labels:
    {{- include "k6-operator.labels" . | nindent 4 }}
    {{- include "k6-operator.customLabels" . | default "" | nindent 4 }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end }}
---
# permissions for end users to edit privateloadzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privateloadzone-editor-role
rules:
- apiGroups:
  - k6.io
  resources:
  - privateloadzones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k6.io
  resources:
  - privateloadzones/status
  verbs:
  - get
---
# permissions for end users to view privateloadzones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privateloadzone-viewer-role
rules:
- apiGroups:
  - k6.io
  resources:
  - privateloadzones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k6.io
  resources:
  - privateloadzones/status
  verbs:
  - get