{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{- include "k6-operator.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "k6-operator.fullname" . }}
    control-plane: "controller-manager"
    {{- with .Values.customLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
{{- end }}
