apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k6-operator.serviceAccountName" . }}
  namespace: {{- include "k6-operator.namespace" . }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "k6-operator.labels" . | nindent 4 }}
    {{- include "k6-operator.customLabels" . | default "" | nindent 4 }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
