{{- if .Values.authProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k6-operator.fullname" . }}-controller-manager-metrics-service
  namespace: {{- include "k6-operator.namespace" . }}
  labels:
    control-plane: "controller-manager"
    app.kubernetes.io/component: controller
    {{- include "k6-operator.labels" . | nindent 4 }}
    {{- include "k6-operator.customLabels" . | default "" | nindent 4 }}
  annotations:
    {{- include "k6-operator.customAnnotations" . | default "" | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: "controller-manager"
{{- end }}
