---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-test
      file: test.js
  initializer:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    securityContext:
      fsGroup: 1
      runAsNonRoot: true
      runAsUser: 12345
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
        - 12345
  starter:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    securityContext:
      fsGroup: 1
      runAsNonRoot: true
      runAsUser: 12345
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
        - 12345
  runner:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    securityContext:
      fsGroup: 1
      runAsNonRoot: true
      runAsUser: 12345
      seccompProfile:
        type: RuntimeDefault
      supplementalGroups:
        - 12345
