apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k6-operator-metrics-auth-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k6-operator-metrics-auth-role
subjects:
  - kind: ServiceAccount
    name: k6-operator-controller
    namespace: k6-operator-system
