apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: k6-operator-controller-manager
  namespace: k6-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /manager
          image: ghcr.io/grafana/k6-operator:controller-v0.0.19
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: quay.io/brancz/kube-rbac-proxy:v0.18.2
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
      serviceAccountName: k6-operator-controller
      terminationGracePeriodSeconds: 10
