apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: k6-operator-controller-manager-metrics-service
  namespace: k6-operator-system
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: controller-manager
