apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k6-operator
  name: k6-operator-controller
  namespace: k6-operator-system
