---
name: "Golang Lint"
permissions: {}
on:
  - push
  - pull_request

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
        with:
          go-version: "1.26.x"
          cache: false
      - name: lint
        uses: golangci/golangci-lint-action@36fe29c8f9dc696b104db0f7d49d1a87d2bbcd5b
        with:
          version: v2.10.1
          args: --timeout=5m
