name: govulncheck
on:
  push:
  pull_request:
  schedule: # weekly on Monday at 09:00 UTC
    - cron: "0 9 * * 1"

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-x64
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version: "1.26.x"
          check-latest: true
      - run: |
          go run golang.org/x/vuln/cmd/govulncheck@v1.3.0 ./...
