---
name: Helm Lint
permissions: {}
on:
  # `ct lint` does not work well with tag references on releases.
  # OTOH, Helm linting on tags is not necessary so long as it
  # happens on push to branches.
  push:
    branches:
      - "**"
    paths:
      - "charts/**"
  pull_request:
    branches-ignore:
      - "release-**/bundle-update"

jobs:
  lint:
    runs-on: ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Helm
        # this is v4.3.0
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112
        with:
          version: v3.21.3

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: 3.13.1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@2e2940618cb426dce2999631d543b53cdcfc8527

      - name: Run chart-testing (lint)
        run: |
          ct lint --config ./charts/ct.yaml
