---
name: "Unit Test"
permissions: {}
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.25.11, 1.26.4]
        k8s_version: [1.27.1, 1.30.0, 1.34.1]
        os: [ubuntu-x64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Test
        run: |
          make test
        env:
          ENVTEST_K8S_VERSION: ${{ matrix.k8s_version }}
